# -*- coding: utf-8 -*-
"""preprocess_data.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kDn_NR-R3V6LeNavnIHH7uQmpybXwUGh

Data Preprocessing: Need to preprocess the stock data for LSTM. This involves scaling the data and preparing it for time series forecasting.
"""

from sklearn.preprocessing import MinMaxScaler
import numpy as np

# Use Min-Max scaling for normalization
scaler = MinMaxScaler(feature_range=(0, 1))
scaled_data = scaler.fit_transform(adj_close)

# Convert the data to a format suitable for LSTM (X, y)
def create_dataset(data, time_step=60):
    X, y = [], []
    for i in range(len(data) - time_step - 1):
        X.append(data[i:(i + time_step)])
        y.append(data[i + time_step, 0])  # We predict the next day's price
    return np.array(X), np.array(y)

time_step = 60  # Look-back window for LSTM
X, y = create_dataset(scaled_data, time_step)

# Reshape X to be 3D for LSTM: [samples, time steps, features]
X = np.reshape(X, (X.shape[0], X.shape[1], X.shape[2]))